_io.TextIOWrapper

list

In [2]:
import numpy

In [3]:
train_list = numpy.loadtxt("code/train.dat", delimiter="	", skiprows=0)

In [4]:
type(train_list)

numpy.ndarray

In [5]:
numpy.shape(train_list)

(18588, 4)

In [6]:
numpy.mean(train_list, axis=0)

array([ 145494.87518829,  145809.75091457,  145171.65590704,
        145491.98111685])

In [7]:
numpy.std(train_list, axis=0)

array([ 13518.72227687,  13540.25656269,  13495.49045088,  13515.95940881])

In [8]:
import sklearn.preprocessing

In [9]:
train_scaled = sklearn.preprocessing.scale(train_list)

In [10]:
train_scaled.mean(axis=0)

array([  8.25225167e-16,  -9.71498902e-16,  -4.78623907e-16,
         1.99336041e-15])

In [11]:
train_scaled.std(axis=0)

array([ 1.,  1.,  1.,  1.])

In [13]:
type(train_scaled)

numpy.ndarray

In [14]:
numpy.shape(train_scaled)

(18588, 4)